name: untitled8
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
    flutter:
      sdk: flutter
    cached_network_image: ^3.3.0
    flutter_svg: ^2.0.9
    intl: ^0.18.0
    intl_phone_field: ^3.2.0
    sign_in_button: ^3.2.0
    hex: ^0.2.0

dev_dependencies:
    flutter_test:
      sdk: flutter
flutter:
    uses-material-design: true
    assets:
      - assets/
      - assets/images/
    fonts:
      - family: Tajawal
        fonts:
          - asset: assets/fonts/TajawalMedium.ttf
            weight: 500
          - asset: assets/fonts/TajawalRegular.ttf
            weight: 400
          - asset: assets/fonts/TajawalBold.ttf
            weight: 700
      - family: Noto Sans Arabic
        fonts:
          - asset: assets/fonts/NotoSansArabicMedium.ttf
            weight: 500
          - asset: assets/fonts/NotoSansArabicBold.ttf
            weight: 700
          - asset: assets/fonts/NotoSansArabicRegular.ttf
            weight: 400
          - asset: assets/fonts/NotoSansArabicSemiBold.ttf
            weight: 600
          - asset: assets/fonts/NotoSansArabicLight.ttf
            weight: 300
      - family: Inter
        fonts:
          - asset: assets/fonts/InterRegular.ttf
            weight: 400
          - asset: assets/fonts/InterMedium.ttf
            weight: 500
          - asset: assets/fonts/InterSemiBold.ttf
            weight: 600
          - asset: assets/fonts/InterLight.ttf
            weight: 300
      - family: Cairo
        fonts:
          - asset: assets/fonts/CairoRegular.ttf
            weight: 400
          - asset: assets/fonts/CairoMedium.ttf
            weight: 500